### PR TITLE
fix(parser): quoted text newline handling

### LINKED ISSUE #623: Monospace quoted text incorrect spans paragraphs
I noticed that format like 

```
here is `some text

down` here
```

Winds up trying to create a `<code>` element that spans the blocks.  That's not conformant with asciidoctor, which just leaves the backticks where they are in the text.

Bold and monospace do not suffer this defect, it seems isolated to just code elements.

### PR DESCRIPTION
**Pull request by gdamore**
Quoted texts (such as bold) should span newlines, but should
not be permitted to span paragraphs or blocks.  This fixes
all of them, and includes parser and renderer validation.

Fixes #623

### CODE REVIEW

**Comment by gdamore** [comment]
I did not copy and modify the rendering tests for HTML to XHTML in this case.  I don't think they add any useful extra value in the XHTML tree, since the parse tree is already validated, and these formats are not different between HTML and XHTML.

File: pkg/parser/quoted_text_test.go [hunk 1]
```diff
@@ -77,6 +77,52 @@ var _ = Describe("quoted texts", func() {
...
+				source := "*some bold\ncontent*"
+				expected := types.DraftDocument{
+					Blocks: []interface{}{
+						types.Paragraph{
+							Lines: [][]interface{}{
+								{
+									types.QuotedText{
+										Kind: types.Bold,
+										Elements: []interface{}{
+											types.StringElement{Content: "some bold\ncontent"},
```
Comment (xcoulon) [inline pkg/parser/quoted_text_test.go:90]: now I realize that the `line` may actually span on multiple lines, but it's not a big deal I guess...
