### PR TITLE
chore(project): Fix errors reported by GolangCI (#219)

### LINKED ISSUE #219: Fix errors reported by GolangCi
See golangCI report:

````
> make lint
cmd/libasciidoc/main.go:26:5: `helpTemplate` is unused (deadcode)
var helpTemplate = `
    ^
pkg/renderer/html5/delimited_block_test.go:285:35: `emtpy` is a misspelling of `empty` (misspell)
                        // asciidoctor will include an emtpy line in the `blockquote` element, I'm not sure why.
                                                       ^
pkg/types/document_attributes.go:71:40: `retrive` is a misspelling of `retrieve` (misspell)
        // if the argument is a pointer, then retrive the value it points to
                                              ^
pkg/types/grammar_types.go:1723:77: `implict` is a misspelling of `implicit` (misspell)
// NewImageAttributes returns a map of image attributes, some of which have implict keys (`alt`, `width` and `height`)
                                                                            ^
pkg/types/grammar_types.go:1761:40: `accross` is a misspelling of `across` (misspell)
// multiple times to the same footnote accross the document)
                                       ^
pkg/types/grammar_types.go:1802:21: `substituion` is a misspelling of `substitution` (misspell)
// Substitution the substituion group to apply when initializing a delimited block
                    ^
pkg/types/grammar_types.go:2182:82: `implict` is a misspelling of `implicit` (misspell)
// NewInlineLinkAttributes returns a map of image attributes, some of which have implict keys (`text`)
````

### PR DESCRIPTION
**Pull request by moorereason**
See individual commits for more details.

Fixes #219

### CODE REVIEW

File: cmd/libasciidoc/main.go [hunk 1]
```diff
@@ -23,8 +23,8 @@ func main() {
 	}
 }
 
-var helpTemplate = `
-{{if or .Runnable .HasSubCommands}}{{.UsageString}}{{end}}`
+// var helpTemplate = `
```
Comment (xcoulon) [inline cmd/libasciidoc/main.go]: let's just remove it completely for now, we don't need it and it's taken from an spf13/viper example anyways, so it shouldn't be hard to find again in the future

**Comment by xcoulon** [comment]
@moorereason I forgot to say thanks (again) when I merged your PR earlier today ;)
